# Generated by Django 4.2.21 on 2025-05-07 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
