# Generated by Django 4.2.21 on 2025-05-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0002_usersubscription_uid_alter_usersubscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='uid',
        ),
    ]
