# Generated by Django 4.2.21 on 2025-05-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0003_remove_usersubscription_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
