# Generated by Django 4.2.21 on 2025-05-07 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0004_alter_usersubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
