# Generated by Django 4.2.21 on 2025-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0005_usersubscription_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
