# Generated by Django 4.2.21 on 2025-05-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone_payments', '0006_alter_subscriptionpayment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
