# Generated by Django 4.2.19 on 2025-02-24 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Boleto', 'Boleto')], default='PIX', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
