# Generated by Django 4.2.20 on 2025-03-07 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_transaction_data_response_transaction_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='platform',
        ),
        migrations.AddField(
            model_name='integration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='gateway',
            field=models.CharField(choices=[('ZeroOne', 'ZeroOne'), ('PagFlex', 'PagFlex')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='integration',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded'), ('CHARGEBACK', 'Chargeback')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='integrations.integration')),
            ],
            options={
                'db_table': 'integrations_requests',
            },
        ),
    ]
