# Generated by Django 4.2.20 on 2025-03-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_remove_integration_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationrequest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
