# Generated by Django 4.2.20 on 2025-03-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_integrationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='gateway',
            field=models.CharField(choices=[('ZeroOne', 'ZeroOne'), ('GhostsPay', 'GhostsPay')], max_length=255),
        ),
    ]
