# Generated by Django 4.2.20 on 2025-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_integration_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='gateway',
            field=models.CharField(choices=[('ZeroOne', 'ZeroOne'), ('GhostsPay', 'GhostsPay'), ('ParadisePag', 'ParadisePag')], max_length=255),
        ),
    ]
