# Generated by Django 4.2.20 on 2025-03-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_integration_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='gateway',
            field=models.CharField(choices=[('ZeroOne', 'ZeroOne'), ('GhostsPay', 'GhostsPay'), ('ParadisePag', 'ParadisePag'), ('Disrupty', 'Disrupty'), ('WolfPay', 'WolfPay'), ('VegaCheckout', 'VegaCheckout'), ('CloudFy', 'CloudFy'), ('TriboPay', 'TriboPay')], max_length=255),
        ),
    ]
