# Generated by Django 4.2.20 on 2025-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_alter_integration_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=255, unique=True)),
                ('response', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integration_samples',
            },
        ),
    ]
