# Generated by Django 4.2.20 on 2025-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_alter_integration_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
