# Generated by Django 4.2.19 on 2025-02-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name-plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('duration', models.CharField(choices=[('month', 'Mensal'), ('year', 'Anual')], default='month', max_length=10, verbose_name='duration')),
                ('is_current', models.BooleanField(default=False, verbose_name='active-plan')),
                ('description', models.TextField(blank=True, verbose_name='description-adm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation-date')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start-date')),
                ('end_date', models.DateTimeField(verbose_name='end-date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active-subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='contracted-plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='deature-description')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.plan', verbose_name='related-plan')),
            ],
        ),
    ]
