# Generated by Django 4.2.19 on 2025-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, verbose_name='duration-value'),
        ),
    ]
