# Generated by Django 4.2.19 on 2025-02-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_duration_value'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='Plan',
        ),
        migrations.AlterModelTable(
            name='planfeature',
            table='plan_feature',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='user_subscription',
        ),
    ]
