# Generated by Django 4.2.20 on 2025-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_uid_alter_plan_id_alter_planfeature_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active-feature'),
        ),
    ]
