# Generated by Django 4.2.20 on 2025-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_planfeature_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('day', 'Diário'), ('month', 'Mensal'), ('year', 'Anual')], default='month', max_length=10, verbose_name='duration'),
        ),
    ]
