# Generated by Django 4.2.21 on 2025-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_delete_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='campaign_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='integration_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='kwai_limit',
            field=models.IntegerField(default=0),
        ),
    ]
