# Generated by Django 4.2.21 on 2025-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_campaign_limit_plan_integration_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amount_sales_aditional',
            field=models.FloatField(default=0.0, verbose_name='amount_sales'),
        ),
        migrations.AddField(
            model_name='plan',
            name='total_sales_month',
            field=models.IntegerField(default=0, verbose_name='total_sales_month'),
        ),
    ]
