# Generated by Django 4.2.19 on 2025-02-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('accounts', '0002_alter_loginlog_browser_alter_loginlog_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
    ]
