# Generated by Django 4.2.20 on 2025-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
