# Generated by Django 4.2.19 on 2025-02-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_account_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginlog',
            table='login_log',
        ),
    ]
