# Generated by Django 4.2.20 on 2025-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
