# Generated by Django 4.2.19 on 2025-02-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_loginlog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='users',
        ),
    ]
