# Generated by Django 4.2.21 on 2025-05-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
