# Generated by Django 4.2.19 on 2025-02-20 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(default='Kwai', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('CPM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_approved', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ads', models.IntegerField(default=0)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ROI', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_views',
            },
        ),
    ]
