# Generated by Django 4.2.19 on 2025-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_transaction'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='integrations',
            field=models.ManyToManyField(related_name='campaigns', to='integrations.integration'),
        ),
    ]
