# Generated by Django 4.2.19 on 2025-02-19 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignview',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 19, 21, 36, 46, 922367, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaignview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
