# Generated by Django 4.2.19 on 2025-02-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_timestamp_campaignview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='campaigns',
        ),
        migrations.AlterModelTable(
            name='campaignview',
            table='campaign_views',
        ),
    ]
