# Generated by Django 4.2.20 on 2025-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='total_ads',
            field=models.FloatField(default=0),
        ),
    ]
