# Generated by Django 4.2.20 on 2025-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_total_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='total_ads',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
