# Generated by Django 4.2.20 on 2025-03-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_total_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='total_ads',
        ),
    ]
