# Generated by Django 4.2.20 on 2025-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_remove_campaign_total_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_ads',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
