# Generated by Django 4.2.20 on 2025-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_alter_campaign_total_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ROI',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
