# Generated by Django 4.2.20 on 2025-03-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_add_campaign_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_canceled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_canceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_abandoned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_chargeback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_rejected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
