# Generated by Django 4.2.20 on 2025-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_campaign_amount_canceled_campaign_total_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount_abandoned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_canceled',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_chargeback',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_rejected',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
