# Generated by Django 4.2.20 on 2025-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_alter_campaign_amount_abandoned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount_approved',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_pending',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
