# Generated by Django 4.2.20 on 2025-04-01 14:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_alter_campaign_amount_abandoned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('total_ads', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_Expense',
                'indexes': [models.Index(fields=['campaign', 'date'], name='campaign_Ex_campaig_765c84_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
