# Generated by Django 4.2.20 on 2025-04-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profit', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('ROI', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('total_views', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_ads', models.DecimalField(decimal_places=8, default=0, max_digits=13)),
                ('total_approved', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('total_refunded', models.IntegerField(default=0)),
                ('total_abandoned', models.IntegerField(default=0)),
                ('total_chargeback', models.IntegerField(default=0)),
                ('total_rejected', models.IntegerField(default=0)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_pending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_chargeback', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_abandoned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='finance_logs', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'finances_logs',
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddIndex(
            model_name='financelogs',
            index=models.Index(fields=['campaign', 'date'], name='finances_lo_campaig_25a0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financelogs',
            unique_together={('campaign', 'date')},
        ),
    ]
