# Generated by Django 4.2.20 on 2025-04-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_financelogs_delete_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='CPC',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='CPV',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='method',
            field=models.CharField(blank=True, choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('CPV', 'CPV')], default=None, max_length=3, null=True),
        ),
    ]
