# Generated by Django 4.2.20 on 2025-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_campaign_cpc_campaign_cpv_campaign_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='CPM',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
