# Generated by Django 4.2.20 on 2025-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_alter_campaign_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='financelogs',
            name='boleto_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='boleto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='credit_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='credit_card_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='debit_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='debit_card_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='pix_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='financelogs',
            name='pix_total',
            field=models.IntegerField(default=0),
        ),
    ]
