# Generated by Django 4.2.20 on 2025-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_financelogs_boleto_amount_financelogs_boleto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='boleto_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='boleto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='credit_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='credit_card_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='debit_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='debit_card_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pix_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pix_total',
            field=models.IntegerField(default=0),
        ),
    ]
