# Generated by Django 4.2.20 on 2025-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_campaign_boleto_amount_campaign_boleto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
