# Generated by Django 4.2.21 on 2025-05-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0031_alter_campaign_options_campaign_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='financelogs',
            name='user_paid',
            field=models.BooleanField(default=False),
        ),
    ]
