services:

  local:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/app:delegated
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    depends_on:
      - psql
      - app
    networks:
      - app_network
    restart: always

  production:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT_SSL:-443}:443"
    volumes:
      - .:/app:delegated
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    depends_on:
      - app
    networks:
      - app_network
    restart: always

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    networks:
      - app_network
    restart: always
      
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
      - ./data/certbot/log:/var/log/letsencrypt
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /app/data/certbot -d ${APP_DOMAIN:-localhost} --non-interactive --agree-tos --email webmaster@${APP_DOMAIN:-localhost}; sleep 12h & wait $${!}; done'
    networks:
      - app_network

  django-command-runner:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    networks:
      - app_network
    entrypoint: ["/scripts/entrypoint.sh"]

  psql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge