services:

  local:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/app:delegated
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    depends_on:
      - psql
      - app
    networks:
      - app_network
    restart: always

  production:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT_SSL:-443}:443"
    volumes:
      - .:/app:delegated
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    depends_on:
      - app
    networks:
      - app_network
    restart: always

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    expose:
      - "8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-psql}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    networks:
      - app_network
    restart: always
      
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/app/data/certbot
      - ./data/certbot/log:/var/log/letsencrypt
    networks:
      - app_network

  django-command-runner:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - APP_AMBIENT=${APP_AMBIENT:-development}
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    networks:
      - app_network
    entrypoint: ["/scripts/entrypoint.sh"]

  psql:
    image: postgres:13-alpine
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge