services:
  app:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-81}:80"
    volumes:
      - ./dockerfiles/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./djangoapp/Public:/djangoapp/Public
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - djangoapp
    networks:
      - djangoapp_network
    restart: always

  djangoapp:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    expose:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    networks:
      - djangoapp_network
    restart: always
      
  django-command-runner:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    networks:
      - djangoapp_network
    entrypoint: ["entrypoint.sh"]

  psql:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    networks:
      - djangoapp_network
    restart: always

networks:
  djangoapp_network:
    driver: bridge