# Generated by Django 4.2.20 on 2025-04-28 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0028_campaign_boleto_amount_campaign_boleto_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kwai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kwai',
            },
        ),
        migrations.CreateModel(
            name='KwaiCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwai_campaigns', to='campaigns.campaign')),
                ('kwai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kwai.kwai')),
            ],
            options={
                'db_table': 'kwai_campaigns',
            },
        ),
    ]
