# Generated by Django 4.2.20 on 2025-04-28 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwai', '0002_kwai_user_id_alter_kwai_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwai',
            name='user_id',
        ),
        migrations.AddField(
            model_name='kwai',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
