# Generated by Django 4.2.20 on 2025-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwai', '0003_remove_kwai_user_id_kwai_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwai',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
