# Generated by Django 4.2.21 on 2025-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwai', '0004_alter_kwai_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwai',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
