# Generated by Django 4.2.19 on 2025-02-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
            ],
        ),
    ]
