<<<<<<< HEAD:app/tutorials/migrations/0002_alter_tutorial_table.py
# Generated by Django 4.2.19 on 2025-02-20 01:14
=======
# Generated by Django 4.2.19 on 2025-02-20 01:00
>>>>>>> d7e3c85 (migrations):djangoapp/tutorials/migrations/0002_alter_tutorial_table.py

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutorial',
            table='tutorials',
        ),
    ]
