# Generated by Django 4.2.19 on 2025-02-20 01:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutorial',
            table='tutorials',
        ),
    ]
