# Generated by Django 4.2.20 on 2025-04-04 01:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorial_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
