# Generated by Django 4.2.21 on 2025-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_register_subject', models.CharField(max_length=250)),
                ('email_recovery_subject', models.CharField(max_length=250)),
                ('email_reminder_subject', models.CharField(max_length=250)),
                ('email_expired_subject', models.CharField(max_length=250)),
                ('email_subscription_paid_subject', models.CharField(max_length=250)),
                ('email_register', models.TextField()),
                ('email_recovery', models.TextField()),
                ('email_reminder', models.TextField()),
                ('email_expired', models.TextField()),
                ('email_subscription_paid', models.TextField()),
                ('require_email_confirmation', models.BooleanField(default=False)),
                ('default_pix', models.TextField()),
                ('firebanking_api_key', models.TextField(blank=True, null=True)),
                ('zeroone_webhook', models.TextField(blank=True, null=True)),
                ('zeroone_webhook_code', models.TextField(blank=True, null=True)),
                ('zeroone_secret_key', models.TextField(blank=True, null=True)),
                ('recaptchar_enable', models.BooleanField(default=False)),
                ('recaptchar_site_key', models.CharField(max_length=250)),
                ('recaptchar_secret_key', models.CharField(max_length=250)),
                ('days_to_reminder', models.IntegerField()),
                ('days_to_expire', models.IntegerField()),
                ('late_payment_interest', models.FloatField(default=2.0)),
                ('daily_late_payment_interest', models.FloatField(default=0.0333)),
            ],
            options={
                'db_table': 'adm_configuration',
            },
        ),
    ]
