# Generated by Django 4.2.21 on 2025-05-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='default_pix',
            field=models.CharField(choices=[('zeroone', 'ZeroOne'), ('firebanking', 'Firebanking')], default='zeroone', max_length=20),
        ),
    ]
