# Generated by Django 4.2.21 on 2025-05-13 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_notification_send',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='start-date')),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(
                    default=False, verbose_name='active-subscription')),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('active', 'Active'), (
                    'pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='plans.plan', verbose_name='contracted-plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Credit Card'), (
                    'DEBIT_CARD', 'Debit Card'), ('BOLETO', 'Boleto')], max_length=20)),
                ('gateway', models.CharField(choices=[
                 ('zeroone', 'ZeroOne'), ('firebanking', 'Firebanking')], default='zeroone', max_length=20)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='payments', to='payments.usersubscription')),
            ],
            options={
                'db_table': 'subscription_payment',
            },
        ),
    ]
