# Generated by Django 4.2.19 on 2025-02-25 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_plan_uid_alter_plan_id_alter_planfeature_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('active', 'Active'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('boleto', 'Boleto')], max_length=20)),
                ('token', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_response', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_payment',
            },
        ),
    ]
