# Generated by Django 4.2.20 on 2025-05-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-created_at']},
        ),
    ]
