# Generated by Django 4.2.21 on 2025-05-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationsend',
            table='notification_send',
        ),
    ]
