# Generated by Django 4.2.21 on 2025-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_notificationsend_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='subscriptionpayment',
            table='subscription_payment',
        ),
    ]
