# Generated by Django 4.2.21 on 2025-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscriptionpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationsend',
            table='subscription_notification_send',
        ),
    ]
