# Generated by Django 4.2.21 on 2025-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentreminderlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentExpireLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_payment_expire_lock',
            },
        ),
    ]
