# Generated by Django 4.2.20 on 2025-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportreply_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
