# Generated by Django 4.2.20 on 2025-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_support_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='user_read',
            field=models.BooleanField(default=False),
        ),
    ]
