# Generated by Django 4.2.20 on 2025-04-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_support_closed_support_user_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='file',
        ),
        migrations.RemoveField(
            model_name='supportreply',
            name='file',
        ),
    ]
