# Generated by Django 4.2.20 on 2025-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_remove_support_file_remove_supportreply_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
