# Generated by Django 4.2.18 on 2025-02-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até'),
        ),
    ]
