# Generated by Django 4.2.18 on 2025-01-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='nome',
            new_name='name',
        ),
    ]
