# Generated by Django 4.2.19 on 2025-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='browser',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='device',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
