# Generated by Django 4.2.18 on 2025-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_nome_accounts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
