# Generated by Django 4.2.18 on 2025-02-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_is_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='failed_login_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa falha'),
        ),
    ]
