# Generated by Django 4.2.18 on 2025-02-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_failed_login_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='failed_login_timestamp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_locked_until',
        ),
    ]
